### ISSUE TITLE
Data (indexing) Per day

### ISSUE THREAD

**Issue by kevinelwell** [jcreameriii/PAS-APM-Dashboard-Package-for-Splunk#4]
Do you have any idea on the size of the data (indexing) per day that gets sent to Splunk? I dont currently use Splunk, so i was looking at the free version. It allows 500mb/day.

**Comment by jcreameriii** [comment]
Hey Kevin,

It's going to vary widely depending on the amount of Vault activity in your environment. This estimate may be off, but its the best I've got right now considering I don't run my lab 24x7. In one of my busiest days, I generated 22,186 syslog messages in a one hour period which was ~19.4MB. If we multiply that out by 24 you're looking at ~466MB per day.

That being said, you may generate way more data per day than I do, or less. But you should at least have a good amount of data to play around with. One thing you could do to limit the number of message/amount of data is to limit the scope of your Vault Audit Action Codes in the dbparm.ini. My lab lets 0-999 messages through right now, that would cut down significantly on the amount of data.

Hope that's helpful!
V/R,
James Creamer

**Comment by jcreameriii** [comment]
FYI, that's multiple feeds of "CyberArk" information, including all Vault Audit Action events, PTA events, VaultMonitor messages and the custom messages being generated from my components.

**Comment by kevinelwell** [comment]
Thank you very much! I will try to get this implemented on my QA environment and see how it goes. IT does not get a lot of activity, but i'd rather start in non-prod first. Thanks so much for creating this and sharing!

Kevin
